"""Added Model PasswordResetToken - removed sponsor_id - removed multiple sponsorships constraint of same user to animal - total amount is now calculated dynamically by RM

Revision ID: 18d1fb55496c
Revises: 209218a036c5
Create Date: 2024-08-27 06:25:42.194910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d1fb55496c'
down_revision = '209218a036c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint('animal_sponsor_id_fkey', type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    with op.batch_alter_table('sponsorship', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_animal_sponsorship', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_spent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_spent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('sponsorship', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_animal_sponsorship', ['user_id', 'animal_id'])

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('animal_sponsor_id_fkey', 'user', ['sponsor_id'], ['id'])

    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
