"""Added fields to Animals and form data table

Revision ID: 89d5c9f96a7a
Revises: 4ca330f1ef46
Create Date: 2024-08-17 10:35:57.601385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d5c9f96a7a'
down_revision = '4ca330f1ef46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=255), nullable=False),
    sa.Column('animal_reference', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('first_time_adopting', sa.String(length=255), nullable=False),
    sa.Column('already_have_pets', sa.String(length=255), nullable=True),
    sa.Column('current_pets_description', sa.Text(), nullable=True),
    sa.Column('interest_reason', sa.Text(), nullable=False),
    sa.Column('met_animal', sa.String(length=255), nullable=False),
    sa.Column('space_for_play', sa.String(length=255), nullable=False),
    sa.Column('able_to_front_vet_bills', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'adoption_form', ['form_id'], ['id'])
        batch_op.drop_column('form_data')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('life_stage', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('breed', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('known_illness', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('known_illness')
        batch_op.drop_column('breed')
        batch_op.drop_column('weight')
        batch_op.drop_column('life_stage')
        batch_op.drop_column('location')

    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('form_id')

    op.drop_table('adoption_form')
    # ### end Alembic commands ###
