"""Added cascade delete to adoption animal adoption form animal image tables. Hopefully project or db do not break upon upgrade -RM

Revision ID: 909e766544d4
Revises: 35167411e166
Create Date: 2024-08-31 17:49:55.453626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909e766544d4'
down_revision = '35167411e166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.drop_constraint('adoption_animal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('animal_image', schema=None) as batch_op:
        batch_op.drop_constraint('animal_image_animal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sponsorship', schema=None) as batch_op:
        batch_op.drop_constraint('sponsorship_animal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sponsorship_animal_id_fkey', 'animal', ['animal_id'], ['id'])

    with op.batch_alter_table('animal_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('animal_image_animal_id_fkey', 'animal', ['animal_id'], ['id'])

    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('adoption_animal_id_fkey', 'animal', ['animal_id'], ['id'])

    # ### end Alembic commands ###
